name: Main
on:
  workflow_dispatch:  # Triggered manually by the user
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'
jobs:
  upload-odp-data:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4' # Specify the Python version you need
      - name: Install poetry
        run: |
          pip install --disable-pip-version-check poetry==1.5.1
          poetry install --remove-untracked
      - name: Download opa_properties_public
        run: poetry run python download_opa_data.py by-col --table opa_properties_public --csv-split-col zip_code
      - name: download rental business_licenses
        run: poetry run python download_opa_data.py by-datetime --table business_licenses --split-by initialissuedate year --where-str "licensetype = 'Rental'"
      - name: rtt_summary
        run: poetry run python download_opa_data.py by-datetime --table rtt_summary --split-by recording_date year
      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip csvs
      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_ACCOUNT_CREDENTIALS }}
          filename: "archive.zip"
          folderId: ${{ secrets.FOLDER_ID }}
          namePrefix: ${{ github.actions }}
          name: open_data_philly_${{ env.NOW }}.zip # optional string
          overwrite: "true" # optional boolean
