name: Main
on:
  workflow_dispatch:  # Triggered manually by the user
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'
jobs:
  upload-odp-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git tag
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H_%M_%S')" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4' # Specify the Python version you need
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Install project
        run: uv pip install -e .
      - name: Download opa_properties_public
        run: uv run download-opa-data by-col --table opa_properties_public --csv-split-col zip_code --skip-save-to-csv
      - name: download rental business_licenses
        run: uv run download-opa-data by-datetime --table business_licenses --split-by initialissuedate year --where-str "licensetype = 'Rental'" --skip-save-to-csv
      - name: rtt_summary
        run: uv run download-opa-data by-datetime --table rtt_summary --split-by recording_date year --skip-save-to-csv --where-str "document_type IN ('DEED', 'DEED_SHERIFF', 'DEED OF CONDEMNATION', 'DEED LAND BANK')"
      - name: Create Release Tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git tag -a "v${{ env.NOW }}" -m "Release for ${{ env.NOW }}"
          git push origin "v${{ env.NOW }}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NOW }}
          name: Open Data Philly DB - ${{ env.NOW }}
          body: |
            Database backup from Open Data Philly
            
            Generated on: ${{ env.NOW }}
          files: |
            open_data_philly.db
